services:
  qdrant:
    container_name: qdrant
    image: qdrant/qdrant:latest
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - type: volume
        source: qdrant_data
        target: /qdrant/storage
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - type: volume
        source: redis_data
        target: /data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: unless-stopped

  chromadb:
    container_name: chromadb
    image: chromadb/chroma:latest
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["*"]
    ports:
      - "8000:8000"
    volumes:
      - type: volume
        source: chromadb_data
        target: /chroma/chroma
    restart: unless-stopped

  chromadb-admin:
    container_name: chromadb-admin
    image: fengzhichao/chromadb-admin:latest
    ports:
      - "3001:3001"
    environment:
      - CHROMA_SERVER_HOST=chromadb
      - CHROMA_SERVER_HTTP_PORT=8000
    depends_on:
      - chromadb
    restart: unless-stopped

volumes:
  qdrant_data:
    driver: local
  redis_data:
    driver: local
  chromadb_data:
    driver: local
